# This is a basic workflow to help you get started with Actions

name: Deploy latest course version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2

    - run: cd $GITHUB_WORKSPACE

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: npm install

    # Runs a set of commands using the runners shell
    - name: Deploy course
      run: npm run deploy
